### ISSUE TITLE
Visual and dynamic progress.

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#1]
### Description
The user would like to see the system track their progress so they can see how much progress they have and how much remains to be completed.

### Acceptance Criteria

- Show a percentage of progress on the current route
- Update automatically
- Completed/uncompleted history for each resource

**Comment by Daniale566** [comment]
- Start a new learning path with multiple resources or topics.
- Complete one or more topics within the learning path.
- Observe the progress indicator to confirm it displays the correct percentage based on completed topics.
- Check that the progress percentage updates automatically as each topic is completed.
- Navigate to the learning path history and verify that each resource shows a completed or uncompleted status.

Validation Criterion:
The system accurately calculates and displays the progress percentage, updating it automatically as topics are completed.
