### ISSUE TITLE
Add a new favorite.

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#11]
### Description
As a user, I would like the system to allow me to save a learning path as a favorite.
### Acceptance criteria
- A course must have a section with a button that allows users to add it to their favorites list.

**Comment by Daniale566** [comment]
- Create or navigate to an existing learning path.
- Locate the "Add to Favorites" button in the course section.
- Click the "Add to Favorites" button.
- Verify that the learning path is added to the user's favorites list.
- Refresh the page or navigate away, then return to confirm the learning path remains in the favorites list.

Validation Criterion:
The system correctly adds the learning path to the user's favorites list and retains it across sessions.
