### ISSUE TITLE
Learning preferences

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#13]
### Description
As a user, I would like to be able to save my learning preferences as part of my account information so I don't have to specify my preferences every time I want a new course.
### Acceptance criteria
- As part of the account information, there must be a section with the user's preferences.
- The user should be able to edit these preferences.

**Comment by dagarcias** [comment]
esta listo en mi rama, falta hacer el merge

**Comment by Daniale566** [comment]
The user must be able to change the preferences based on the test
- There is a section for user preferences
- For this story the user tried to enter the "take the test" and change the original and modified values
