### ISSUE TITLE
New educational material.

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#14]
### Description
As an administrator, the system must allow me to add new learning content to the platform index.
### Acceptance criteria
- The administrator menu must allow entering new educational material.
- The materials entered must have among the information, its type of content, its theme and its source.

**Comment by Daniale566** [comment]
As and administrator we tried to put new educational material (resources) in the DB
- we create a new administrator menu for the eduacational resources
- now the administrator can create new resources and put the: Type of content, theme and source
