### ISSUE TITLE
Learning path 

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#15]
### Description
As a user, I find it necessary that the system generates a learning route depending on the instructions I give it, based on my preferences and the topic I want to study.

### Acceptance criteria
- The system must generate a learning path.
- You must take into account the instructions given by the user.
- You must take into account the preferences given in the user's account profile.

**Comment by Daniale566** [comment]
- For this story we tried to generate a learning path based on the preferences of the user
- The server must be able to save the user responses and preferences (we tried and the save is correctly based)
- the account preferences its saved in the DB
