### ISSUE TITLE
Create new route.

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#17]
### Description
As a user I must be able to create a new learning route.

### Acceptance criteria
- The user must be able to create a course whenever they want.
- The course must contain materials related to whatever the user needs to learn.
- The course must be based on the answers to the form.

**Comment by Daniale566** [comment]
- For this story, we try to create many courses as the user wants, to verify the creations of the routes
- Also we tried to put material on the course and the user should be able to look at the link, and click, the redirect should be working correctly
