### ISSUE TITLE
Form creation

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#18]
### Description
 As an administrator, I would like the application to have a built-in form that allows analyzing user preferences.

### Acceptance criteria
- The form must contain questions that allow selecting a type of learning for the user
- The form must save the answers and then deliver a type of learning that will be stored in the user's account

**Comment by Daniale566** [comment]
for this story the user should be able to answer the questions in the form
- For this we create new responses and a better UX
- the user can now answer the question and then recive a type of learning that its stored in the users column
