### ISSUE TITLE
Rating educational material

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#24]
## Description
As a user, I want to rate educational materials I have completed, so that I can provide feedback and help others gauge the quality and relevance of the content.
## Acceptance criteria 
- Users can rate each educational material they have completed on a scale of 1 to 5.
- Upon rating, a confirmation message appears, indicating that the rating has been successfully saved.

**Comment by Daniale566** [comment]
- Navigate to a completed educational material in the learning path.
- Select a rating on a scale of 1 to 5 for the material.
- Submit the rating.
- Verify that a confirmation message appears, indicating that the rating has been successfully saved.
- Refresh the page or return to the material to confirm the saved rating is displayed correctly.

Validation Criterion:
The system allows users to submit a rating and displays a confirmation message upon successful save.
