### ISSUE TITLE
Achievement system

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#25]
## Description:
As a user, I want to earn medals for completing all the content in a learning path,
so that I can feel motivated and rewarded for my progress in completing educational challenges.

## Acceptance criteria

- When a user completes all the content within a learning path, they will be automatically unlock a button that will award a medal for that route. This includes marking all contents as completed and updating the progress for each content item.
- The awarded medals will be visible in the user's profile under the "Medals" section. Each medal will display the name of the learning path, the date it was awarded, a visual representation of the medal (icon or image).

**Comment by Daniale566** [comment]
- Begin a learning path and mark each content item as completed until the entire path is finished.
- Verify that upon completing the last item, a "Claim Medal" button or similar appears, allowing the user to receive a medal.
- Click the "Claim Medal" button to award the medal.
- Navigate to the user’s profile and locate the "Medals" section.
- Confirm that the awarded medal is displayed with:
- The name of the learning path,
- The date it was awarded,
- A visual representation of the medal (icon or image).

Validation Criterion:

The system automatically displays a "Claim Medal" button upon completion of all content, and the awarded medal correctly appears in the user’s profile with all required details.
