### ISSUE TITLE
 Skip modules already known by the user

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#3]
### Description
As a user, I would like it to be possible to mark the topics or items that I already know or have developed as already seen, validating my progress on my route. 
### Acceptance Criteria
- The learning route must have a check button per course, so the user can check it as already viewed or known.

**Comment by Daniale566** [comment]
Test Steps:

- Create a new learning path with multiple topics or items.
- Navigate to a topic within the learning path.
- Click the "Mark as Seen" check button on the topic.
- Verify that the topic status updates to "seen" or "known" after clicking the button.
- Refresh the page and confirm that the "seen" status persists.

Validation Criterion:
The system correctly updates and saves the "seen" status for each topic in the user’s learning path.
