### ISSUE TITLE
Log in creation.

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#4]
### Description
As a user, I would like to be able to enter my account on the platform so I can continue with my progress and the status of my account.
### Acceptance criteria
- The user must be able to log into the platform using their previously registered email and password.

**Comment by Daniale566** [comment]
Before: we tried to use Auth0 as a login form (bug section)

after: We prefer to uses the django base DB for contain users information
- the user now can login correctly if they were registred previously
