### ISSUE TITLE
Delete learning route.

### ISSUE THREAD

**Issue by cortegons** [jsuarezb1808/IntelligenceWay#8]
### Description
As a user, I must be able to delete my progress at will for courses that I am no longer interested in.
### Acceptance criteria
- The user must be able to delete a course that they do not wish to continue.
- Before deleting, the system must ask to confirm that you are sure of your decision.

**Comment by Daniale566** [comment]
- We tried to create a new user, and create a new route
- The user tried to delete the route and the message for confirmation and the delete of the learning path its correctly workign
